apiVersion: v1
kind: Service
metadata:
  name: sean-prod-1
  namespace: default
spec:
  type: NodePort        
  selector:
    app: sean-bg
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sean-preview-1
  namespace: default
spec:
  type: NodePort       
  selector:
    app: sean-bg-1
  ports:
  - port: 80
    targetPort: 8080