apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: k8s-assessment
type: Opaque
data:
  # user: admin
  username: cHNxbGFkbWlu
  # password: securepassword123
  password: WW91clNlY3VyZUF6dXJlUGFzc3dvcmQh