apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring # Must be in the monitoring namespace to be picked up easily
  labels:
    release: monitoring
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - backend-a
          - backend-b
  namespaceSelector:
    matchNames:
      - sean-k8s-assessment
  endpoints:
    - port: http # This matches the port name in your Deployment YAML
      path: /metrics
      interval: 15s